### ISSUE TITLE
Postgis 2.4

### ISSUE THREAD

**Issue by skinkie** [go-spatial/tegola#143]
http://postgis.net/2017/09/02/postgis-2.4.0beta1/

Would _3661, Mapbox vector tile output support via ST_AsMVT (Björn Harrtell / Carto)_ help in this project?

**Comment by ARolek** [comment]
@skinkie I have been watching ST_AsMVT but leveraging it opens up several things to consider:

- We would still need to support our current approach for PostGIS versions pre 2.4 so now we have two implementations to manage.
- From what I can tell, ST_AsMVT returns an encoded `tile` rather than a `layer`. Tegola is designed to support multiple data providers so our `MVTProvider` interface expects back `mvt.Layer` types rather than `mvt.Tile` types. This allows tegola to mash up layers from various providers. If we used ST_AsMVT we would need to decode the response from PostGIS to extract the `mvt.Layer` before passing up the stack.
- I think the feature tag approach ST_AsMVT has chosen will take some time to adopt with the rest of the ecosystem tooling. 

Near term we don't have any plans on leveraging ST_AsMVT but we're going to keep watching it.
