### ISSUE TITLE
Move z,x,y values to from int to uint

### ISSUE THREAD

**Issue by ARolek** [go-spatial/tegola#312]
Z/X/Y values should never be negative and therefor should be of type `uint`. This change will need to be implemented in the `server` package for both `HandleMapLayerZXY` and `HandleMapZXY` methods, the `cache` interface and sub packages as well as other packages that accept any z/x/y values (i.e. atlas package: `Map.FilerLayersByZoom()`)

**Comment by ear7h** [comment]
I can work on this. 

Also after reading more on the coordinate system, I saw there are bounds on the max X and Y values for each tile coordinate. The `parseURI` function doesn't check for it, I'm not sure if this is corrected else where.

**Comment by ARolek** [comment]
@ear7h much appreciated! 

So the X/Y in the Z/X/Y tile scheme does not refer to a coordinate on the tile, but rather references a zoom, row and column in the [slippy map tile scheme](https://wiki.openstreetmap.org/wiki/Slippy_map_tilenames) which is quad tree where at zoom 0 there is 1 tile, zoom 1 there are 4 tiles, zoom 2 there are 16 tiles, etc. etc. The Z/X/Y values are then converted into a tile [Extent](https://github.com/terranodo/tegola/blob/v0.6.0/geom/slippy/tile.go#L36) at a later stage which is then used for filtering features that intersect with the extent by data provider.

**Comment by ear7h** [comment]
@ARolek right, so there are max values for the columns an rows. Should there be a check for this as well?

**Comment by ARolek** [comment]
Not quite sure what the max values are. I’m not too concerned about that check for now. Main thing is no negative values.

**Comment by pnorman** [comment]
Each zoom is 2^z tiles wide, so 0 <= x < 2^z and 0 <= y < 2^z

**Comment by pnorman** [comment]
If you pass an invalid request through to PostGIS and it's far enough from sane (e.g. z=0, x=2^31-1) it might cause an error when the query is run, as well as being slow, and if you reject early you can give a HTTP 400 error with a suitable message instead of a vague 500 error message. They'll also appear in the logs differently, which matters. I've seen a case of a bad scraper triggering alarms when it caused a huge spike in the error rate from its invalid requests, and a suitable error code would have helped ops realize it was someone else's problem, not ours.

**Comment by ear7h** [comment]
@pnorman Tegola gives a 200 response for a request to this path: `/maps/zoning/road/0/3/3`. I've looked at fixing this, I believe it can be taken care of by using adding a bounds checking middlewear.

@ARolek should this be a new issue?

**Comment by gdey** [comment]
Let's make that a new issue.
