### ISSUE TITLE
Demo on website shows errors

### ISSUE THREAD

**Issue by skinkie** [go-spatial/tegola#346]
![image](https://user-images.githubusercontent.com/502394/36797456-4bccf78c-1ca8-11e8-89fe-7faa061b2c83.png)

**Comment by gdey** [comment]
Hi, @skinkie thanks for reporting this. We are aware of these issues. They are due to the tolerance and the simplification algo we are using. One of the big things in our v0.6.0 release (which was released yesterday) is the ability to turn off simplification on a per layer basis. We are working to update the demo site with the new version. We are looking at changing out the simplification algo in a near future release.

**Comment by gdey** [comment]
This is fixed now.
