### ISSUE TITLE
PostGIS JSON field

### ISSUE THREAD

**Issue by sanfilippopablo** [go-spatial/tegola#380]
Hello! I have a JSON field in my PostGIS table that I want to put as an object in the properties of the feature. However, the json is being put as a string. Is it possible to parse it to an object?

**Comment by ARolek** [comment]
@sacontreras currently the MVT spec has no treatment specifically for objects or lists, which is why the JSON is being encoded as a string. There's a discussion on the spec repo for this topic [here](https://github.com/mapbox/vector-tile-spec/issues/75). 

Near term I think you will need to use JSON.parse() on the client side to convert the string to a JSON object. Alternatively you could pull the important parameters out of the JSON object in your ProviderLayer SQL and encode the values as normal tags.

**Comment by sacontreras** [comment]
@ARolek While I do find this topic interesting, I think you've confused me with the original poster (@sanfilippopablo).    👍

**Comment by sanfilippopablo** [comment]
@ARolek yes, `JSON.parse()` client side is what I'm doing right now, I just wanted to avoid that overhead. This isn't an issue with tegola currently, then. I'll close. Thanks!
