### ISSUE TITLE
Tegola Lambda Gives Mapbox Unimplemented type: 7 Error 

### ISSUE THREAD

**Issue by scottkehler** [go-spatial/tegola#496]
I successfully deployed tegola_lambda to AWS Lambda and use an API gateway to request tiles. However, when my mapbox script requests tiles from Lambda, it gives "Unimplemented type: 7". Based on what I have read, this seems to be an issue with the response tiles not being zipped, or not being zipped correctly. This issue may be related to #438 .

In the past I have successfully used tegola to serve tiles to a website that uses mapbox. I am wondering if the lambda implementation of tegola is compressing the tiles differently than the MacOS/linux versions of tegola - causing this error?

**Comment by ARolek** [comment]
@scottkehler I believe that error can show up for several reasons if the tile is not encoded correctly. Can you share the endpoint so I can take a look?

**Comment by scottkehler** [comment]
This is the endpoint I have been testing with: https://15jk7dxj0e.execute-api.us-east-1.amazonaws.com/dev/maps/bonn/road1/{z}/{x}/{y}.pbf

**Comment by ARolek** [comment]
@scottkehler Just a quick look at the responses and it looks like you still need to configure the binary media types as described under [Configuring API Gateway](https://github.com/go-spatial/tegola/tree/master/cmd/tegola_lambda#configuring-api-gateway). Here's the blurb I'm referring to:

- On the left, under the APIs section, locate "Settings" under the configured API.
Under "Binary Media Types" click "Add Binary Media Type".
  - Input "/" as the value. This is necessary as tegola returns protocol buffers, which are a binary format. Without this configuration API gateway will return the vector tile payloads as base64 encoded strings.
  - Click "Save Changes".

**Comment by scottkehler** [comment]
I did add the "/" in binary media types, so that doesn't appear to be the issue.

**Comment by ARolek** [comment]
@scottkehler try changing the value to `*/*`. If you try to request one of your tiles directly it's coming back as a base64 encoded string which is why mapbox GL is throwing the error. For example:

```bash
$ curl https://15jk7dxj0e.execute-api.us-east-1.amazonaws.com/dev/maps/bonn/road1/12/12/12.pbf
GgwKBXJvYWQxKIAgeAI=
```
That response payload should not be a string but binary.

**Comment by scottkehler** [comment]
Changing it from / to */* appears to have worked. Thanks for the help!

**Comment by ARolek** [comment]
@scottkehler beautiful. I will update the readme. 

Congrats on the deployment btw! You're the first person besides the `go-spatial` team that I know of who has done a tegola lambda deployment.

**Comment by ARolek** [comment]
Looks like the README.md file was correct but when GH parsed it for presentation they removed the `*` from the `*/*` piece. It's now fixed.

**Comment by conorrfarrell** [comment]
For future reference if anyone is looking for an explanation on the process of binary media types, I solved this with serverless using mapbox:

I personally have failed to find good internal serverless packages that support binary. This is now all handled directly within serverless/APIG.

(1) Your serverless package

The biggest pitfall is that default Accept headers are set to `*/*`, which is why you see a lot of documentation surrounding setting your Binary Media Type to `*/*` within APIG. Do not do this, this means that every request you send will be encoded, which will mess up your cors approach and give you a false response. Add this to your YAML and within you API in `API gateway -> <your api> -> settings -> Binary media type` you will see your MIME type added once deployed.

```yaml
provider:
  apiGateway:
    binaryMediaTypes:
      - 'application/vnd.mapbox-vector-tile'
```

This is all you need to add to your serverless file.

(2) Your functions, NODEJS Typescript:

```js
import serverless from 'serverless-http';
import cors from 'cors';
import express from 'express';
import api from './api';

const app = express();


app.use(cors());
app.use('/', api);

export const api: serverless.Handler = serverless(app, {
  binary: ['application/vnd.mapbox-vector-tile'],
});
```

Note here I am using the serverless-http package, the reason this is important is because it allows you to set the accepted MIME types.

```js
import express, { Request, Response, NextFunction } from 'express';
import axios from 'axios';

const router = express.Router();

router.get('/ping', (req: Request, res: Response) => {
  res.send('Pong');
});

router.get('/layers/:gsdata/:z/:x/:y', async (req: Request, res: Response, next: NextFunction) => {
  const {
    z, x, y, gsdata,
  } = req.params;

  try {
    const response = await axios(
      { method: 'get', url, responseType: 'stream' },
    );

    res.set({
      'Content-Type': 'application/vnd.mapbox-vector-tile',
      'Access-Control-Allow-Origin': '*',
      'Access-Control-Allow-Methods': 'GET, POST, OPTIONS, PUT, PATCH, DELETE',
    });

    response.data.pipe(res);
  } catch (err) {
    console.error(err);
    next(err);
  }
});

export default router;
```

As you can see here we need to set the Content type and make sure we are returning a stream and piping that into our response. This basically tells lambda we want this to be encoded into a base64.

Why base64? -

`Base64 encoding schemes are commonly used when there is a need to encode binary data that needs to be stored and transferred over media that are designed to deal with ASCII. This is to ensure that the data remain intact without modification during transport`

If this is not done you will end up losing packets across APIG. Hence why your data may not work if sent as a raw stream.

(3) Your client Accept header

If you do not add an accept header to your request, from the client, you will get a base64 back, if you add an accept header of application/vnd.mapbox-vector-tile this will tell APIG to decode the format on response

```js
const mapConfig = {
  container: mapContainer.current,
  style: `${OS_VTS}/resources/styles?key=${OS_TOKEN}`,
  center: [lng, lat],
  zoom,
  transformRequest: (url_) => {
    if (url_.includes('<start of your api url>')) {
      return {
        url: url_,
        headers: { Accept: 'application/vnd.mapbox-vector-tile' },
      };
    }
    return { url: url_ };
  },
};
```

Replace all cases of `application/vnd.mapbox-vector-tile` with your accepted binary media type and hey presto 🎉 🎉 🎉

**Comment by ARolek** [comment]
@conorrfarrell thanks for the write-up! Also note that you can deploy tegola_lambda behind an Application Load Balancer (ALB) now instead of using API Gateway. I have found the deployment is easier, but you do lose some of the API Gateway features for sure.
