### ISSUE TITLE
How to use limit clause in configuration file ?

### ISSUE THREAD

**Issue by capan** [go-spatial/tegola#569]
Hi,
I want to do simplifying while sending queries to PostgreSQL. But I can't use LIMIT clause in configuration file. When I try to run Tegola I get **could not register providers: error fetching geometry type for layer (temperature_stations_simple): ERROR: syntax error at or near "LIMIT" (SQLSTATE 42601)** error. 

Thanks

**Comment by ARolek** [comment]
@capan this error is happening because tegola can't infer the geometry type for that layer. This is because the SQL parser is not that smart. The best way around this is to set the `geometry_type` config for that provider layer. Take a look at [this section](https://tegola.io/documentation/configuration/#postgis-1) in the documentation.

**Comment by ARolek** [comment]
@capan does this work around suffice for now? I would like to close the issue if it does.

**Comment by capan** [comment]
Hi, @ARolek  I couldn't find time to check your solution. Instead I've found a work around in database side. I'm closing the issue now. After I check your solution, if error persists I can re-open the issue again.
