### ISSUE TITLE
GEOMETRY error when trying Tegola with a geopackage

### ISSUE THREAD

**Issue by kartogishenko** [go-spatial/tegola#571]
I get an error saying "Error: could not register providers: unsupported geometry type: GEOMETRY" when trying to tegola_windows_amd64_cgo version 0.8.1 on a geopackage file. The gpkg file contains only one table that lists as a LineString25D when opened in QGis (works perfectly) geometry column is geom, srid is 3857.

This is my config-file:

    [webserver] port = ":8082"

    [cache] type = "file" basepath = "C:\Tegola\cache"

    [[providers]] name = "gsd" type = "gpkg" filepath = "C:\Tegola\data\gsd.gpkg"

        [[providers.layers]] name = "gsdvol" tablename = "vol"

    [[maps]] name = "roads"

        [[maps.layers]] provider_layer = "gsd.gsdvol" min_zoom = 11 max_zoom = 19

Is this a bug or am I just configuring it wrong?

**Comment by ARolek** [comment]
@kartogishenko anyway I can get access to the geopackage to recreate it? I would suspect what's going on here is that the `GEOMETRY` type is too generic and tegola wants to know if it's a polygon, line string, point, etc.

**Comment by kartogishenko** [comment]
Sure, here it comes. Doubblechecked there is only one kind of geometry in the fil.
[geopackage.zip](https://github.com/go-spatial/tegola/files/2836950/geopackage.zip)

**Comment by ARolek** [comment]
@kartogishenko i got it working. A few things:

- tegola does not have support for the generic "geometry" type. This is because MVT does not have support for it (also called a geometry collection). A layer must have a single geometry type, not a heterogenous mixture. In the case of this geopackage, the `vol` layer has a type of `LINESTRING`
- The geopackage appears to have a non standard structure (missing `fid`) so the auto generated SQL from tegola does not work out of the box. I was able to export your geopackage using QGIS, setting the geometry type to `LINESTRING` and everything works fine (screen shot below). I have also attached the new geopackage for your review.
- Where did you obtain this geopackage file? I'm interested in knowing what's creating this structure in case it shows up again. 
- This issue also brings to attention that tegola needs to support the `geometry_type` override for geopackage like we do for PostGIS. This is a different issue. 

New Geopackage: [gsd-2.gpkg.zip](https://github.com/go-spatial/tegola/files/2849329/gsd-2.gpkg.zip)


<img width="1796" alt="screen shot 2019-02-10 at 12 22 37 pm" src="https://user-images.githubusercontent.com/667850/52539057-a61a5580-2d2e-11e9-8e54-0b6bdafa6e6b.png">

For convenience the URL in the screen shot is: http://localhost:8082/#11.64/55.6392/13.7449

**Comment by kartogishenko** [comment]
Hi, thank you for looking in to it. The Geopackage was created using FME Desktop 2018.1 and the software might have som issues when exporting to geopackage, according to its support forum. When comparing your rework of my geopackage with the original one I notice that mine has the geometrytype LineString25D and yours has LineString. This I cannot correct in FME, unfortunately. I do get it to work using the same method as you did when creating the geopackage from QGis so I just have to use that method for now. Thank you!

**Comment by ARolek** [comment]
@kartogishenko I have not used FME myself so I don't have any insight into some of the data conversion nuances. 

> When comparing your rework of my geopackage with the original one I notice that mine has the geometrytype LineString25D and yours has LineString.

This sounds like a bug in FME as `LineString25D` is not a valid [Geometry Type according to the Geopackage spec](http://www.geopackage.org/spec/#geometry_types). Maybe let them know?

Glad you have a work around. Please close the issue unless you have any other questions.
