### ISSUE TITLE
Using ST_Transform in SQL query

### ISSUE THREAD

**Issue by gorbypark** [go-spatial/tegola#635]
I have a table with an 26910 SRID so I'm attempting to transform it to 4326 to use with tegola.  My query in config.toml is like this
```sql = "SELECT ST_AsBinary(ST_Transform(geom, 4326)) AS geom, id FROM my_schema.my_table WHERE geom && !BBOX!"```
I get no results returned.  If I use the exact query on a table with an SRID of 4326 (and even keeping the ST_Transform and all), everything works, so I'm confident that I haven't messed up my mapbox-gl config when displaying the results.  Is it possible to use ST_Transform to reproject on the fly?  I'd love to avoid having to create a view in the database for every table.

**Comment by ARolek** [comment]
@gorbypark tegola supports querying data that's in either 4326 or 3857 projections. During request time, tegola is going to create a bounding box based on one of those two projections and replace the `!BBOX!` token with the tile bounds. You wont be able to do the reprojection during the `SELECT` query because the bounding box that's sent to your query wont match your data's projection and thus you will get no hits. 

I would suggest creating a materialized view which reprojects the data into 3857 and have tegola operate against it.

**Comment by pnorman** [comment]
> Is it possible to use ST_Transform to reproject on the fly?

You have to reproject the bounding box.

**Comment by gorbypark** [comment]
> You have to reproject the bounding box.

```toml
sql = "SELECT ST_AsBinary(ST_Transform(geom, 4326)) AS geom, id FROM my_schema.my_table WHERE geom && ST_Transform(!BBOX!, 26910)"
```

That did the trick, thanks folks!

**Comment by ARolek** [comment]
@pnorman thanks for chiming in!
