### ISSUE TITLE
Question: referencing SQL Files in config.toml

### ISSUE THREAD

**Issue by jay-manday** [go-spatial/tegola#678]
Hey there,

I've been having a bunch of fun tinkering around with tegola, really nice and easy to use. One Q I had though is if it's possible to use file paths to individual sql queries rather than having them inline in the config.toml. I tried using something like below but no dice, it would be nice to have something like this in the config. Theres probably a stupid simple way to do this that i totally overlooked. 

what i tried in my config.toml:
```
sql = "$(eval ./path/to/my/quey.sql)"
```

Thanks

**Comment by gdey** [comment]
Unfortunately, there currently isn't. The ${ENV_NAME} will only do environment substitution at current. However, we could add this feature. We would need a way to distinguish between a raw SQL string and a file path. Also, what file paths are allowed. As this could be used as a vector of attack, to read privileged files, if Tegola is run as a privileged user, but the config is editable by nonprivileged user. Currently, we spit out the SQL to consol if there is a bad SQL or the SQL debug environmental variables are set.

**Comment by jay-manday** [comment]
Hey @gdey thanks for the lickity split response, ahh gotcha. IF it were to be done one way we could do it would be to have some sort of keyword to parse before the select statement do something like the following
inline as default
```
sql = """
SELECT yada FROM yada.yada
"""
```

with file paths
```
sql = """path
./path/to/my/query.sql
"""
```

as for checking for permissions, thats a good point, one way to check if the sql or config file has the proper permissions though could be with something like `os.Stat` which will give you info to a given file's permissions. heres a simple example i pulled from SO https://stackoverflow.com/questions/45429210/how-do-i-check-a-files-permissions-in-linux-using-go

**Comment by ARolek** [comment]
One way to implement this would be to introduce the config param `sql_path` rather than overload the `sql` attribute. 

Alternatively, if you're dealing with a verbose config and you could potentially use [SQL VIEWS](https://www.postgresql.org/docs/9.2/sql-createview.html). This way you would manage the SQL at the database layer and then from the tegola config you could call the VIEW. A VIEW is really just a stored select so it's convenient to use if you expect your SQL to change, but you can keep the return values consistent in the tegola config.

**Comment by jay-manday** [comment]
@ARolek Thats a really good idea re: views! I'll give it a go
