### ISSUE TITLE
Add support for built-in Prometheus Metrics

### ISSUE THREAD

**Issue by mapl** [go-spatial/tegola#714]
This proposal is intended to start a short discussion whether it is feasible to add built-in support for Prometheus Metrics.

The well written API documentation should make it easy to expose relevant internal metrics and consume them with third party system.

Basic Metrics like CPU and Memory Consumption come to my mind as well as specific Tegola Metrics like served Tiles and certainly many more.

**Comment by ARolek** [comment]
Support for better logging has been discussed numerous times (#215 #691). Maybe we can start exploring the logger interface more so various logging services can be implemented much like we have support for different providers. I'm absolutely a +1 for getting this streamlined across the software.

**Comment by ARolek** [comment]
This issue is going to start being worked on. It will come in 3 phases and each phase will have its own issue:

- [ ] **Configuration and default observability:** Introduce Prometheus metric reporting into tegola. Enhancements to the tegola configuration file will be made to enable metric reporting and exposing the necessary API endpoints that Prometheus will operate against.
- [ ] **Cache hits / miss & HTTP request observability:** Enhance the request middleware to report cache stats and HTTP request stats. 
- [ ] **Cache and data provider observability:** Enhance the data and cache providers to report various connection statistics.

I'm looking forward to having some observability in tegola!
