### ISSUE TITLE
uri_prefix breaks with a trailing slash

### ISSUE THREAD

**Issue by jleedev** [go-spatial/tegola#735]
When the uriPrefix has a trailing slash, the API server works but the static files become broken.

This breaks:

```
¶ cat config.toml 
[webserver]
uri_prefix = "/tegola/"
[…]
¶ docker-compose restart 
Restarting gnis_tegola_1 ... done
¶ curl localhost:8080/tegola/capabilities 
{"version":"v0.12.1", …
¶ curl localhost:8080/tegola/
404 page not found
```

But this works:

```
¶ cat config.toml 
[webserver]
uri_prefix = "/tegola"
[…]
¶ docker-compose restart 
Restarting gnis_tegola_1 ... done
¶ curl localhost:8080/tegola/capabilities 
{"version":"v0.12.1", …
¶ curl localhost:8080/tegola/
<!DOCTYPE html>…
```

**Comment by ARolek** [comment]
Hmmm, well that's annoying. I'm not quite sure what's causing this, but maybe it has to do with setting up the router group:

https://github.com/go-spatial/tegola/blob/7f0e7e66089ead2823a65c50baa995b5c0d9a487/server/server.go#L59

**Comment by gdey** [comment]
I think the issue is here:
https://github.com/go-spatial/tegola/blob/7f0e7e66089ead2823a65c50baa995b5c0d9a487/server/viewer.go#L30-L34

See how we are blindly striping the URIPrefix, which means that when there is a "/" at the end; we end up stripping the starting "/" from the path. We Should probably strip the "/" from `URIPrefix` before using `strings.TrimPrefix`.

On line 29 do something like:

```go

if len(URIPrefix) > 0 && URIPrefix[len(URIPrefix)-1] == '/'  {
      URIPrefix = URIPrefix[:len(URIPrefix)-1]
}

```
And change line 30 to check against `""` instead.
