### ISSUE TITLE
SSL support

### ISSUE THREAD

**Issue by ARolek** [go-spatial/tegola#82]
In order to support HTTP2 we need to support SSL.

**Comment by sacontreras** [comment]
This will be especially useful in my case since I am currently rev'ing Tegola Mobile to support the new Android API 28 release, which disallows cleartext rxtx over http by default. I can work around it in the meantime but I would rather not.

**Comment by ear7h** [comment]
@sacontreras I created a branch with https support through the config, if you'd like to try it out.

@ARolek you should check it as well but I think it would be best to have refactor of the `server` package. I'm thinking we should implement the pattern of passing in a `dict.Dicter` rather than setting global variables.

(branch here)[https://github.com/go-spatial/tegola/tree/16bad8cb070f0d6160fbc2baccf2ce8e3e91360d]

**Comment by ARolek** [comment]
@ear7h I'm open for leveraging the Dicter interface to instantiate the server. I can't recall why I was setting global vars but there is an issue that was causing problems with the config strategy before.

**Comment by sacontreras** [comment]
Sorry for the delay.  Will get to testing this some time over the weekend.

**Comment by ear7h** [comment]
Currently working on this, for the latest version of tegola. Here's a reference to why we need ssl for http2 (it's not  immediately stated when searching for h2)

https://http2.github.io/faq/#does-http2-require-encryption

> Does HTTP/2 require encryption?
>
>No. After extensive discussion, the Working Group did not have consensus to require the use of encryption (e.g., TLS) for the new protocol.
>
> However, some implementations have stated that they will only support HTTP/2 when it is used over an encrypted connection, and currently no browser supports HTTP/2 unencrypted

**Comment by ARolek** [comment]
As of v0.11.0 tegola supports SSL
