### ISSUE TITLE
v0.18.0 Docker image has no viewer UI

### ISSUE THREAD

**Issue by jchamberlain** [go-spatial/tegola#945]
As of the changes in #940/#941, the image that is pushed on release loads only the following HTML at /:

```
<pre>
<a href=".keep">.keep</a>
</pre>
```

I'm guessing this is because the "Publish Docker container" step does not include `context: .`, and thus is working on the Git context, which does not include the local filesystem changes like the addition of `ui/dist`.

**Comment by ARolek** [comment]
@jchamberlain thanks for the report. There's one other report of someone having issues with the viewer: https://github.com/go-spatial/tegola/issues/942

**Comment by jchamberlain** [comment]
Thanks @ARolek, I just left a comment there. It appears to be an unrelated issue: the output of `tegola version` always says "ui viewer: viewer not build" even when it did build successfully.

**Comment by ARolek** [comment]
To follow up on @jchamberlain report, the following step in the CI appears to be where the issue is happening:

https://github.com/go-spatial/tegola/blob/096b5d90328ed4b494bedf9aa780a5b065797122/.github/workflows/on_release_publish.yml#L209-L216

And the `context` @jchamberlain is talking about is documented [here](https://github.com/docker/build-push-action#git-context)

**Comment by ARolek** [comment]
@manastyretskyi can you take a quick look at this one? Seems like all we need to do is add `context: .` to the action.

**Comment by manastyretskyi** [comment]
@ARolek I will try to take a look at it later today
